### ISSUE TITLE
HomeAssistant crash - ValueError: bad marshal data

### ISSUE THREAD

**Issue by diricxbart** [home-assistant/hassio-supervisor#1415]
**Home Assistant release with the issue:**
```
~ $ hassio info
arch: armv7
channel: stable
hassos: "3.7"
homeassistant: 0.103.5
hostname: hassio
logging: info
machine: raspberrypi3
supervisor: "193"
supported_arch:
- armv7
- armhf
timezone: Europe/Brussels
```

**Operating environment (HassOS/Generic):**
HassOS

**Supervisor logs:**
```
hassio supervisor logs
20-01-05 10:31:27 INFO (MainThread) [__main__] Initialize Hass.io setup
20-01-05 10:31:28 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/armv7-hassio-supervisor with version 193
20-01-05 10:31:28 INFO (MainThread) [__main__] Setup HassIO
20-01-05 10:31:28 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
20-01-05 10:31:29 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
20-01-05 10:31:29 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: de.pengutronix.rauc - /
20-01-05 10:31:29 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.NetworkManager - /org/freedesktop/NetworkManager/DnsManager
20-01-05 10:31:29 INFO (MainThread) [hassio.host.info] Update local host information
20-01-05 10:31:29 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-01-05 10:31:29 INFO (MainThread) [hassio.host.services] Update service information
20-01-05 10:31:29 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-01-05 10:31:29 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-01-05 10:31:29 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-01-05 10:31:29 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-01-05 10:31:29 INFO (MainThread) [hassio.host.services] Reload local service hassos-apparmor.service
20-01-05 10:31:29 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
20-01-05 10:31:29 INFO (SyncWorker_2) [hassio.docker.interface] Attach to homeassistant/armv7-hassio-dns with version 1
20-01-05 10:31:29 INFO (MainThread) [hassio.dns] Update resolv from Supervisor
20-01-05 10:31:29 WARNING (MainThread) [hassio.dns] Ignore invalid DNS Server: dns://2a02:1800:100::45:2
20-01-05 10:31:29 WARNING (MainThread) [hassio.dns] Ignore invalid DNS Server: dns://2a02:1800:100::45:1
20-01-05 10:31:29 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
20-01-05 10:31:29 INFO (MainThread) [hassio.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-01-05 10:31:29 INFO (SyncWorker_2) [hassio.docker.interface] Clean hassio_dns application
20-01-05 10:31:54 INFO (SyncWorker_2) [hassio.docker.dns] Start DNS homeassistant/armv7-hassio-dns with version 1
20-01-05 10:31:54 INFO (SyncWorker_3) [hassio.docker.interface] Attach to homeassistant/raspberrypi3-homeassistant with version 0.103.5
20-01-05 10:31:55 INFO (MainThread) [hassio.hassos] Detect HassOS 3.7 on host system
20-01-05 10:31:55 INFO (SyncWorker_1) [hassio.docker.hassos_cli] Found HassOS CLI homeassistant/armv7-hassio-cli with version 15
20-01-05 10:31:56 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-01-05 10:31:56 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/core repository
20-01-05 10:31:57 INFO (MainThread) [hassio.store] Load add-ons from store: 62 all - 62 new - 0 remove
20-01-05 10:31:57 INFO (MainThread) [hassio.addons] Found 5 installed add-ons
20-01-05 10:31:57 INFO (SyncWorker_4) [hassio.docker.interface] Attach to homeassistant/armv7-addon-check_config with version 3.1
20-01-05 10:31:57 INFO (SyncWorker_1) [hassio.docker.interface] Attach to homeassistant/armv7-addon-duckdns with version 1.10
20-01-05 10:31:57 INFO (SyncWorker_8) [hassio.docker.interface] Attach to homeassistant/armv7-addon-ssh with version 8.1
20-01-05 10:31:57 INFO (SyncWorker_11) [hassio.docker.interface] Attach to homeassistant/armv7-addon-configurator with version 4.2
20-01-05 10:31:57 INFO (SyncWorker_2) [hassio.docker.interface] Attach to homeassistant/armv7-addon-samba with version 9.0
20-01-05 10:31:57 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-01-05 10:31:57 INFO (MainThread) [hassio.snapshots] Found 5 snapshot files
20-01-05 10:31:57 INFO (MainThread) [hassio.discovery] Load 0 messages
20-01-05 10:31:57 INFO (MainThread) [hassio.ingress] Load 0 ingress session
20-01-05 10:31:57 INFO (MainThread) [hassio.secrets] Load Home Assistant secrets: 3
20-01-05 10:31:57 INFO (MainThread) [__main__] Run Hass.io
20-01-05 10:31:57 INFO (MainThread) [hassio.api] Start API on 172.30.32.2
20-01-05 10:31:57 INFO (MainThread) [hassio.addons] Phase 'initialize' start 0 add-ons
20-01-05 10:31:57 INFO (MainThread) [hassio.addons] Phase 'system' start 0 add-ons
20-01-05 10:31:57 INFO (MainThread) [hassio.addons] Phase 'services' start 3 add-ons
20-01-05 10:31:57 INFO (SyncWorker_17) [hassio.docker.interface] Clean addon_core_samba application
20-01-05 10:31:59 INFO (SyncWorker_18) [hassio.docker.interface] Clean addon_core_duckdns application
20-01-05 10:32:00 INFO (SyncWorker_1) [hassio.docker.interface] Clean addon_core_ssh application
20-01-05 10:32:38 INFO (SyncWorker_17) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-samba with version 9.0
20-01-05 10:32:50 INFO (SyncWorker_18) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-duckdns with version 1.10
20-01-05 10:32:55 INFO (SyncWorker_1) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-ssh with version 8.1
20-01-05 10:33:00 INFO (SyncWorker_5) [hassio.docker.interface] Start homeassistant/raspberrypi3-homeassistant
20-01-05 10:33:23 ERROR (MainThread) [hassio.homeassistant] Home Assistant has crashed!
20-01-05 10:33:23 INFO (MainThread) [hassio.addons] Phase 'application' start 1 add-ons
20-01-05 10:33:23 INFO (SyncWorker_12) [hassio.docker.interface] Clean addon_core_configurator application
20-01-05 10:33:34 INFO (SyncWorker_12) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-configurator with version 4.2
20-01-05 10:33:41 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
20-01-05 10:33:41 INFO (MainThread) [hassio.core] Hass.io is up and running
20-01-05 12:33:41 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-01-05 12:40:21 INFO (MainThread) [hassio.host.info] Update local host information
20-01-05 12:40:21 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-01-05 12:40:21 INFO (MainThread) [hassio.host.services] Update service information
20-01-05 12:40:21 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-01-05 12:40:21 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-01-05 12:40:21 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-01-05 13:33:41 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-01-05 13:33:41 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-01-05 13:33:43 INFO (MainThread) [hassio.store] Load add-ons from store: 62 all - 0 new - 0 remove
20-01-05 14:33:41 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-01-05 14:47:01 INFO (MainThread) [hassio.host.info] Update local host information
20-01-05 14:47:01 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-01-05 14:47:01 INFO (MainThread) [hassio.host.services] Update service information
20-01-05 14:47:01 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-01-05 14:47:01 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-01-05 14:47:01 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-01-05 16:33:41 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-01-05 16:33:41 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-01-05 16:33:41 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-01-05 16:33:43 INFO (MainThread) [hassio.store] Load add-ons from store: 62 all - 0 new - 0 remove
20-01-05 16:53:41 INFO (MainThread) [hassio.host.info] Update local host information
20-01-05 16:53:41 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-01-05 16:53:41 INFO (MainThread) [hassio.host.services] Update service information
20-01-05 16:53:41 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-01-05 16:53:41 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-01-05 16:53:41 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-01-05 18:27:44 INFO (MainThread) [hassio.api.security] /homeassistant/logs access from core_ssh
20-01-05 18:28:00 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh
```

**HomeAssistant logs:**
```
~ $ hassio homeassistant logs
Fatal Python error: initsite: Failed to import the site module
Error processing line 1 of /usr/local/lib/python3.7/site-packages/google_api_core-1.15.0-py3.8-nspkg.pth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
EOFError: marshal data too short
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site.py", line 579, in <module>
    main()
  File "/usr/local/lib/python3.7/site.py", line 566, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/local/lib/python3.7/site.py", line 349, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/local/lib/python3.7/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/local/lib/python3.7/site.py", line 178, in addpackage
    import traceback
  File "/usr/local/lib/python3.7/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/lib/python3.7/linecache.py", line 8, in <module>
    import functools
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
ValueError: bad marshal data (invalid reference)
```

**Description of problem:**
Home Assistant crashes upon starting.

Based on the log I suspect this issue to be caused because PEP 552 has been implemented, which adds extra 4 bytes to the .pyc header; but this version of setuptools is not aware of that yet. I think setuptools should be updated to v38.4.1.

See these links for further information on this bug:
- https://github.com/pypa/setuptools/issues/1257
- https://stackoverflow.com/a/55167875

**Comment by pvizeli** [comment]
Thanks for this information. I had also that issue and fixed it with an `hassio su repair`. I will look into this

**Comment by diricxbart** [comment]
Hi,

I tried your suggestion, but it failed. Here are the logs:
```
20-01-06 19:02:34 INFO (MainThread) [hassio.api.security] /supervisor/repair access from core_ssh
20-01-06 19:02:34 INFO (MainThread) [hassio.core] Start repairing of Hass.io Environment
20-01-06 19:02:34 INFO (SyncWorker_14) [hassio.docker] Prune stale containers
20-01-06 19:02:35 INFO (SyncWorker_14) [hassio.docker] Prune stale images
20-01-06 19:03:38 INFO (SyncWorker_14) [hassio.docker] Prune stale builds
20-01-06 19:03:38 INFO (SyncWorker_14) [hassio.docker] Prune stale volumes
20-01-06 19:03:38 INFO (SyncWorker_14) [hassio.docker] Prune stale networks
20-01-06 19:03:38 INFO (MainThread) [hassio.addons] Found 2 add-ons to repair
20-01-06 19:03:38 INFO (MainThread) [hassio.addons] Start repair for add-on: core_configurator
20-01-06 19:03:38 INFO (SyncWorker_4) [hassio.docker.interface] Pull image homeassistant/armv7-addon-configurator tag 4.2.
20-01-06 19:04:29 INFO (MainThread) [hassio.addons] Start repair for add-on: core_check_config
20-01-06 19:04:29 INFO (SyncWorker_12) [hassio.docker.interface] Pull image homeassistant/armv7-addon-check_config tag 3.1.
20-01-06 19:05:43 ERROR (SyncWorker_12) [hassio.docker.interface] Can't install homeassistant/armv7-addon-check_config:3.1 -> 404 Client Error: Not Found ("no such image: homeassistant/armv7-addon-check_config:3.1: No such image: homeassistant/armv7-addon-check_config:3.1").
20-01-06 19:05:43 ERROR (MainThread) [hassio.addons] Can't repair core_check_config
20-01-06 19:05:43 INFO (SyncWorker_0) [hassio.docker.interface] Remove image homeassistant/armv7-addon-check_config with latest and 3.1
20-01-06 19:05:43 INFO (MainThread) [hassio.addons.addon] Remove add-on data folder /data/addons/data/core_check_config
20-01-06 19:05:44 INFO (MainThread) [hassio.addons] Add-on 'core_check_config' successfully removed
20-01-06 19:05:44 INFO (MainThread) [hassio.homeassistant] Repair Home Assistant 0.103.5
20-01-06 19:05:44 INFO (SyncWorker_5) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.103.5.
20-01-06 19:07:02 ERROR (SyncWorker_5) [hassio.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:0.103.5 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi3-homeassistant:0.103.5: No such image: homeassistant/raspberrypi3-homeassistant:0.103.5").
20-01-06 19:07:02 ERROR (MainThread) [hassio.homeassistant] Repairing of Home Assistant fails
20-01-06 19:07:02 INFO (MainThread) [hassio.hassos] Repair HassOS CLI 15
20-01-06 19:07:02 INFO (SyncWorker_11) [hassio.docker.interface] Pull image homeassistant/armv7-hassio-cli tag 15.
20-01-06 19:07:05 INFO (SyncWorker_11) [hassio.docker.interface] Tag image homeassistant/armv7-hassio-cli with version 15 as latest
20-01-06 19:07:07 INFO (MainThread) [hassio.supervisor] Repair Supervisor 193
20-01-06 19:07:11 INFO (MainThread) [hassio.core] Finished repairing of Hass.io Environment
```

If I try to update homeassistant, then this also fails similarly:
```
20-01-06 19:18:47 INFO (MainThread) [hassio.api.security] /homeassistant/update access from core_ssh
20-01-06 19:18:47 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.103.5
20-01-06 19:18:47 INFO (SyncWorker_0) [hassio.docker.interface] Update image homeassistant/raspberrypi3-homeassistant:0.103.5 to homeassistant/raspberrypi3-homeassistant:0.103.5
20-01-06 19:18:47 INFO (SyncWorker_0) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.103.5.
20-01-06 19:18:56 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:0.103.5 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi3-homeassistant:0.103.5: No such image: homeassistant/raspberrypi3-homeassistant:0.103.5").
20-01-06 19:18:56 WARNING (MainThread) [hassio.homeassistant] Update Home Assistant image fails
20-01-06 19:19:10 INFO (MainThread) [hassio.api.security] /homeassistant/logs access from core_ssh
20-01-06 19:19:20 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh
```

**Comment by diricxbart** [comment]
I downgraded homeassistant from latest 0.103.5 to 0.103.4 using `hassio homeassistant update --version=0.103.4`:
```
20-01-06 19:40:15 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.103.4
20-01-06 19:40:15 INFO (SyncWorker_18) [hassio.docker.interface] Update image homeassistant/raspberrypi3-homeassistant:0.103.5 to homeassistant/raspberrypi3-homeassistant:0.103.4
20-01-06 19:40:15 INFO (SyncWorker_18) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.103.4.
20-01-06 19:58:08 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.103.4
```
Next I redid the repair:
```
~ $ hassio su repair
Processing... Done.
Command completed successfully.
```
Logs now indicate the repair completed without errors:
```
20-01-06 21:44:24 INFO (MainThread) [hassio.core] Start repairing of Hass.io Environment
20-01-06 21:44:24 INFO (SyncWorker_7) [hassio.docker] Prune stale containers
20-01-06 21:44:24 INFO (SyncWorker_7) [hassio.docker] Prune stale images
20-01-06 21:44:34 INFO (SyncWorker_7) [hassio.docker] Prune stale builds
20-01-06 21:44:34 INFO (SyncWorker_7) [hassio.docker] Prune stale volumes
20-01-06 21:44:34 INFO (SyncWorker_7) [hassio.docker] Prune stale networks
20-01-06 21:44:35 INFO (MainThread) [hassio.addons] Found 1 add-ons to repair
20-01-06 21:44:35 INFO (MainThread) [hassio.addons] Start repair for add-on: core_configurator
20-01-06 21:44:35 INFO (SyncWorker_2) [hassio.docker.interface] Pull image homeassistant/armv7-addon-configurator tag 4.2.
20-01-06 21:45:11 INFO (MainThread) [hassio.homeassistant] Repair Home Assistant 0.103.4
20-01-06 21:45:11 INFO (SyncWorker_0) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.103.4.
20-01-06 21:47:13 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh
20-01-06 21:50:07 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh
20-01-06 22:03:45 INFO (MainThread) [hassio.hassos] Repair HassOS CLI 15
20-01-06 22:03:45 INFO (SyncWorker_15) [hassio.docker.interface] Pull image homeassistant/armv7-hassio-cli tag 15.
20-01-06 22:03:47 INFO (SyncWorker_15) [hassio.docker.interface] Tag image homeassistant/armv7-hassio-cli with version 15 as latest
20-01-06 22:03:47 INFO (MainThread) [hassio.supervisor] Repair Supervisor 193
20-01-06 22:03:48 INFO (MainThread) [hassio.core] Finished repairing of Hass.io Environment
```
But when I start homeassistant, I'm back to where I started with the original error:
```
~ $ hassio homeassistant start
Processing... Done.

Error: Unknown Error, see logs
~ $ hassio homeassistant logs
Fatal Python error: initsite: Failed to import the site module
Error processing line 1 of /usr/local/lib/python3.7/site-packages/google_api_core-1.15.0-py3.8-nspkg.pth:
Traceback (most recent call last):
...
...
ValueError: bad marshal data (unknown type code)
```

**Comment by pvizeli** [comment]
We have no setup tools inside because the package is installed. If you disable the component they import this module, everthing work?

**Comment by diricxbart** [comment]
homeassistant 0.103.6 is released, I tried updating to that version and now my homeassistant is up and running again!

But things are not fully fixed, The "Configurator" add-on no longer works, when checking the log I see the exact same type of error:
```
Traceback (most recent call last):
  File "/usr/local/bin/hass-configurator", line 3, in <module>
    import re
  File "/usr/local/lib/python3.7/re.py", line 122, in <module>
    import enum
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
```
My understanding of this error is that there are *.pyc files with a format incompatible with the current _compile_bytecode. Now here it concerns a standard Python module: 'enum'. 

I don't know the details on the hassio update flow, but on my system there's somehow a mismatch between the provided pyc file format in the docker images and the Python pyc bytecode loading scripts.

I triead a `hassio su repair`, the log shows it 'repairs' the configurator addon, but testing afterwards shows the same issue...

**Comment by pvizeli** [comment]
It could be that your SD card is going defect and if they create the container, varia bytes are corrupt. The best thing on docker, all or no one has an issue, if someone has an issue, there are local issues.
