### ISSUE TITLE
Latest docker tag not refer to V.195 

### ISSUE THREAD

**Issue by Glingling** [home-assistant/hassio-supervisor#1443]
**Home Assistant release with the issue:**

0.104.2

**Operating environment (HassOS/Generic):**

Debian 10 (buster) up-to-date 

**Supervisor logs:**

20-01-20 13:47:04 INFO (MainThread) [hassio.core] Hass.io reboot detected
20-01-20 13:47:04 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
20-01-20 13:47:04 INFO (MainThread) [hassio.core] Hass.io is up and running
20-01-20 13:47:04 INFO (MainThread) [hassio.homeassistant] Setup Home Assistant
20-01-20 13:47:04 INFO (SyncWorker_3) [hassio.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.104.2.
20-01-20 13:47:05 INFO (SyncWorker_3) [hassio.docker.interface] Tag image homeassistant/qemux86-64-homeassistant with version 0.104.2 as latest
20-01-20 13:47:05 INFO (MainThread) [hassio.homeassistant] Home Assistant docker now installed
20-01-20 13:47:05 INFO (MainThread) [hassio.homeassistant] Start Home Assistant
20-01-20 13:47:05 WARNING (MainThread) [hassio.homeassistant] Home Assistant is already running!
20-01-20 13:47:05 INFO (SyncWorker_6) [hassio.docker.interface] Cleanup images: ['homeassistant/qemux86-64-homeassistant:landingpage']
20-01-20 13:47:17 INFO (MainThread) [__main__] Initialize Hass.io setup
20-01-20 13:47:17 INFO (MainThread) [__main__] Setup HassIO
20-01-20 13:47:17 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor:latest with version 195
20-01-20 13:47:17 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.systemd1 on /org/freedesktop/systemd1
20-01-20 13:47:17 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
20-01-20 13:47:17 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.hostname1 on /org/freedesktop/hostname1
20-01-20 13:47:17 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
20-01-20 13:47:17 INFO (MainThread) [hassio.utils.gdbus] Introspect de.pengutronix.rauc on /
20-01-20 13:47:17 ERROR (MainThread) [hassio.utils.gdbus] DBus return error: b'Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name de.pengutronix.rauc was not provided by any .service files\n'
20-01-20 13:47:17 WARNING (MainThread) [hassio.dbus.rauc] Can't connect to rauc
20-01-20 13:47:17 INFO (MainThread) [hassio.host.info] Update local host information
20-01-20 13:47:17 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-01-20 13:47:18 INFO (MainThread) [hassio.host.services] Update service information
20-01-20 13:47:18 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-01-20 13:47:18 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-01-20 13:47:18 INFO (MainThread) [hassio.host.services] Reload local service hassio-apparmor.service
20-01-20 13:47:18 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
20-01-20 13:47:18 INFO (SyncWorker_0) [hassio.docker.interface] Attach to homeassistant/qemux86-64-homeassistant with version 0.104.2
20-01-20 13:47:18 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/core/almond/config.json: Service almond not found @ data['discovery'][0]. Got 'almond'
20-01-20 13:47:18 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/core/git_pull/config.json: does not match regular expression for dictionary value @ data['schema']['git_command']. Got 'list(pull|reset)'
20-01-20 13:47:18 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/core/letsencrypt/config.json: does not match regular expression for dictionary value @ data['schema']['challenge']. Got 'list(dns|http)'
does not match regular expression for dictionary value @ data['schema']['dns']['provider']. Got 'list(dns-cloudflare|dns-cloudxns|dns-digitalocean|dns-dnsimple|dns-dnsmadeeasy|dns-gehirn|dns-google|dns-linode|dns-luadns|dns-nsone|dns-ovh|dns-rfc2136|dns-route53|dns-sakuracloud)?'
20-01-20 13:47:18 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/a0d7b954/appdaemon/config.json: does not match regular expression for dictionary value @ data['schema']['log_level']. Got 'list(trace|debug|info|notice|warning|error|fatal)?'
20-01-20 13:47:18 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/core repository
20-01-20 13:47:18 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-01-20 13:47:18 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/core/almond/config.json: Service almond not found @ data['discovery'][0]. Got 'almond'
20-01-20 13:47:18 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/core/git_pull/config.json: does not match regular expression for dictionary value @ data['schema']['git_command']. Got 'list(pull|reset)'
20-01-20 13:47:18 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/core/letsencrypt/config.json: does not match regular expression for dictionary value @ data['schema']['challenge']. Got 'list(dns|http)'
does not match regular expression for dictionary value @ data['schema']['dns']['provider']. Got 'list(dns-cloudflare|dns-cloudxns|dns-digitalocean|dns-dnsimple|dns-dnsmadeeasy|dns-gehirn|dns-google|dns-linode|dns-luadns|dns-nsone|dns-ovh|dns-rfc2136|dns-route53|dns-sakuracloud)?'
20-01-20 13:47:18 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/a0d7b954/appdaemon/config.json: does not match regular expression for dictionary value @ data['schema']['log_level']. Got 'list(trace|debug|info|notice|warning|error|fatal)?'
20-01-20 13:47:18 INFO (MainThread) [hassio.store] Load add-ons from store: 59 all - 59 new - 0 remove
20-01-20 13:47:18 INFO (MainThread) [hassio.addons] Found 1 installed add-ons
20-01-20 13:47:18 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
20-01-20 13:47:18 INFO (MainThread) [hassio.snapshots] Found 0 snapshot files
20-01-20 13:47:18 INFO (MainThread) [hassio.discovery] Load 0 messages
20-01-20 13:47:18 INFO (MainThread) [hassio.ingress] Load 8 ingress session
20-01-20 13:47:18 INFO (MainThread) [__main__] Run Hass.io
20-01-20 13:47:18 INFO (MainThread) [hassio.misc.dns] Start DNS port forwarding for host add-ons
20-01-20 13:47:18 INFO (MainThread) [hassio.api] Start API on 172.30.32.2
20-01-20 13:47:18 INFO (MainThread) [hassio.addons] Phase 'initialize' start 0 add-ons
20-01-20 13:47:18 INFO (MainThread) [hassio.core] Hass.io reboot detected
20-01-20 13:47:18 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
20-01-20 13:47:18 INFO (MainThread) [hassio.core] Hass.io is up and running
20-01-20 13:50:48 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
20-01-20 13:50:58 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 144, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 38, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/api/addons.py", line 146, in list
    ATTR_AVAILABLE: addon.available,
  File "/usr/src/hassio/hassio/addons/model.py", line 90, in available
    return self._available(self.data)
  File "/usr/src/hassio/hassio/addons/model.py", line 469, in _available
    if StrictVersion(self.sys_homeassistant.version) < StrictVersion(version):
  File "/usr/local/lib/python3.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/local/lib/python3.7/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '0.102.0.dev'

**Description of problem:**
After a fresh install I install Configurator addons, the install works but when I want to go again on the Addons Store I have this message :
![Screenshot from 2020-01-20 15-14-10](https://user-images.githubusercontent.com/18287390/72733141-87a41780-3b97-11ea-96ef-906448936d76.png)
I see on portainer two image of hassio-supervisor : 
![Screenshot from 2020-01-20 15-10-10](https://user-images.githubusercontent.com/18287390/72733202-a9050380-3b97-11ea-83f9-040241a88840.png)
And the latest not corresponding with the real latest version...
![Screenshot from 2020-01-20 15-16-45](https://user-images.githubusercontent.com/18287390/72733306-e2d60a00-3b97-11ea-9941-45afbf8d3114.png)
On the Hass.io -> System I can't udate the supervisor....

**Comment by Glingling** [comment]
I use the script from "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" for the install. So how i can use specific version tag ?

**Comment by pvizeli** [comment]
Thanks, it's fixed now
